### ISSUE TITLE
10.1101-2020.03.18.20038059.md is empty

### ISSUE THREAD

**Issue by cgreene** [ismms-himc/covid-19_sinai_reviews#4]
This file has no contents.

**Comment by cornhundred** [comment]
This was addressed with this commit https://github.com/ismms-himc/covid-19_sinai_reviews/commit/28f740527a2a206d1f730ef9c20328553dc68e7c

**Comment by cornhundred** [comment]
FYI, the very bottom of the Observable notebook lists reviews that are not being processed correctly (usually a naming issue) https://observablehq.com/@ismms-himc/covid-19-sars-cov-2-preprints-from-medrxiv-and-biorxiv
